name: Test connect to repository and docker

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
                       ls
                       cd /mnt/odoo_14/addons/estim
                       modules=$(git log -m -1 --name-only --pretty="format:" HEAD | cut -d'/' -f1 | grep . | uniq | paste -sd "," -)
                       list_update=${modules/.github,/""}
                       docker exec -u root -t -i odoo_14 /bin/bash
                       /usr/bin/python3 /usr/bin/odoo -c /etc/odoo/odoo.conf -d odoo_14 -u echo $list_update --stop-after-init
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password:  ${{ secrets.PASSWORD_HOST }}
