name: Test connect to repository and docker

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
                       ls
                       cd /mnt/odoo_14/addons/estim
                       modules=$(git log -m -1 --name-only --pretty="format:" HEAD | cut -d'/' -f1 | grep . | uniq | paste -sd "," -)
                       replace_git=${modules/.github/""}
                       echo $replace_git
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password:  ${{ secrets.PASSWORD_HOST }}
