name: Test connect to repository and docker

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
                       ls
                       cd /mnt/odoo_14/addons/estim
                       modules=$(git log -m -1 --name-only --pretty="format:" HEAD | cut -d'/' -f1 | grep . | uniq | paste -sd "," -)
                       list_update=${modules/.github,/""}
                       docker ps
                       winpty docker exec -it odoo_14 bash
                       ls
                       docker ps
                       echo "test1"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password:  ${{ secrets.PASSWORD_HOST }}
